[project]
name = "get_a_priori_objects_points"
version = "0.4.1"
description = ""
requires-python = ">=3.11"
dependencies = [
"numpy",
"cv_shared @ git+https://github.com/AlexanderAMedvedev/cv_shared.git@0.3.0"
]

[project.optional-dependencies]
dev = ["pytest"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
